version: '3.2'
services: 

 chrome:
   image: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
   working_dir: /tests
   command: "npm i && npx cypress run --browser chrome"
   volumes:
     - ./:/tests