version: '3.2'
services: 

 e2e-chrome:
   build: ./
   command: "--browser chrome"

 e2e-firefox:
   build: ./
   command: "--browser firefox --config video=false"

 e2e-edge:
   build: ./
   command: "--browser edge"