version: '3.2'
services: 

  e2e-chrome:
   build: .
   command: "-b chrome"
   volumes:
    - ./:./
    
  e2e-firefox:
   build: .
   command: "-b firefox -c video=false"
   volumes:
    - ./:./

  e2e-edge:
   build: .
   command: "-b edge"
   volumes:
    - ./:./