version: '3.8'

services:
  e2e-chrome:
    build: .
    command: "-b chrome"
    working_dir: /e2e-chrome
    volumes:
      - ./:/e2e-chrome
      - chrome-videos:/e2e-chrome/cypress/videos
      - chrome-screenshots:/e2e-chrome/cypress/screenshots

  e2e-firefox:
    build: .
    command: "-b firefox -c video=false"
    working_dir: /e2e-firefox
    volumes:
      - ./:/e2e-firefox
      - firefox-screenshots:/e2e-firefox/cypress/screenshots

  e2e-edge:
    build: .
    command: "-b edge"
    working_dir: /e2e-edge
    volumes:
      - ./:/e2e-edge
      - edge-videos:/e2e-edge/cypress/videos
      - edge-screenshots:/e2e-edge/cypress/screenshots

volumes:
  chrome-videos:
  chrome-screenshots:
  firefox-screenshots:
  edge-videos:
  edge-screenshots: