version: '3.8'

services:
  e2e-chrome:
    command: "-b chrome"
    working_dir: /e2e-chrome
    volumes:
      - ./:/e2e-chrome
      - ./artifacts/chrome/videos:/e2e-chrome/cypress/videos
      - ./artifacts/chrome/screenshots:/e2e-chrome/cypress/screenshots

  e2e-firefox:
    command: "-b firefox -c video=false"
    working_dir: /e2e-firefox
    volumes:
      - ./:/e2e-firefox
      - ./artifacts/firefox/videos:/e2e-firefox/cypress/videos
      - ./artifacts/firefox/screenshots:/e2e-firefox/cypress/screenshots

  e2e-edge:
    command: "-b edge"
    working_dir: /e2e-edge
    volumes:
      - ./:/e2e-edge
      - ./artifacts/edge/videos:/e2e-edge/cypress/videos
      - ./artifacts/edge/screenshots:/e2e-edge/cypress/screenshots