version: '3.2'
services: 

  e2e-chrome:
   build: .
   command: "-b chrome"
   working_dir: /e2e-chrome
   volumes:
    - ./artifacts/chrome/videos:/e2e-chrome/cypress/videos
    - ./artifacts/chrome/screenshots:/e2e-chrome/cypress/screenshots
    
  e2e-firefox:
   build: .
   command: "-b firefox -c video=false"
   working_dir: /e2e-firefox
   volumes:
    - ./artifacts/firefox/videos:/e2e-firefox/cypress/videos
    - ./artifacts/firefox/screenshots:/e2e-firefox/cypress/screenshots

  e2e-edge:
   build: .
   command: "-b edge"
   working_dir: /e2e-edge
   volumes:
    - ./artifacts/edge/videos:/e2e-edge/cypress/videos
    - ./artifacts/edge/screenshots:/e2e-edge/cypress/screenshots